const COPY_FIELDS=[["heroCopy","Texto do Hero"],["cityCopy","Texto João Pessoa"],["soundCopy","Texto da música"],["refsCopy","Texto dos cards de artistas"],["lineupIntro","Introdução dos DJs"],["venueCopy","Texto do local"],["ticketNote","Texto do ingresso"],["finalCopy","Texto final"]];
const SECTION_LABELS={hero:"Hero",runner:"Faixa animada",statement:"João Pessoa",sound:"Música",references:"Cards de artistas",djs:"DJs",date:"Data do evento",venue:"Local + Google Maps",tickets:"Ingressos",countdown:"Contagem regressiva",faq:"FAQ",final:"CTA final"};
let config=null;const $=id=>document.getElementById(id);
function status(msg,ok=false){$("status").textContent=msg;$("status").classList.toggle("ok",ok)}
function showLogin(msg=""){loginView.classList.remove("hidden");appView.classList.add("hidden");loginError.textContent=msg}
function showApp(){loginView.classList.add("hidden");appView.classList.remove("hidden")}
function buildCopyFields(){for(const lang of ["pt","es"]){const panel=document.querySelector(`[data-panel="${lang}"]`);panel.innerHTML="";COPY_FIELDS.forEach(([key,label])=>{const d=document.createElement("div");d.className="field";d.innerHTML=`<label>${label}</label><textarea id="copy-${lang}-${key}"></textarea>`;panel.appendChild(d)})}}
function buildSections(){sectionSwitches.innerHTML=Object.entries(SECTION_LABELS).map(([key,label])=>`<label class="switch"><span>${label}</span><input type="checkbox" data-section-key="${key}"></label>`).join("")}
function setPreview(container,url,label){container.innerHTML="";if(url){const img=new Image();img.src=url;img.alt=label;container.appendChild(img)}else container.textContent=label}
function fill(c){config=c;for(const k of ["lot","price","date","eventDateLabel","eventTimeLabel","city","venue","wa","sympla","insta","email","address","mapLink","mapEmbedUrl","vognPhoto","glitzyPhoto"])if($(k))$(k).value=c[k]??"";genresPt.value=(c.genres?.pt||[]).join("\n");genresEs.value=(c.genres?.es||[]).join("\n");mapPreview.src=c.mapEmbedUrl||"";setPreview(vognPreview,c.vognPhoto,"DJ VOGN");setPreview(glitzyPreview,c.glitzyPhoto,"DJ GLITZY");for(const lang of ["pt","es"]){for(const [key] of COPY_FIELDS){const el=$(`copy-${lang}-${key}`);if(el)el.value=c.copy?.[lang]?.[key]??""}}vognTextPt.value=c.copy?.pt?.vognText||"";vognTextEs.value=c.copy?.es?.vognText||"";glitzyTextPt.value=c.copy?.pt?.glitzyText||"";glitzyTextEs.value=c.copy?.es?.glitzyText||"";document.querySelectorAll("[data-section-key]").forEach(x=>x.checked=c.sections?.[x.dataset.sectionKey]!==false)}
async function load(){status("Carregando…");const r=await fetch("/api/admin/content");if(r.status===401)return showLogin();const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){showLogin(d.error||"Não foi possível carregar o painel");return}fill(d.config);showApp();status("Conteúdo carregado",true)}
function collect(){const c=structuredClone(config||{});for(const k of ["date","eventDateLabel","eventTimeLabel","city","venue","wa","sympla","insta","email","address","mapLink","mapEmbedUrl","vognPhoto","glitzyPhoto"])c[k]=$(k).value.trim();c.lot=Number(lot.value||1);c.price=Number(price.value||0);c.genres={pt:genresPt.value.split("\n").map(x=>x.trim()).filter(Boolean),es:genresEs.value.split("\n").map(x=>x.trim()).filter(Boolean)};c.copy=c.copy||{pt:{},es:{}};for(const lang of ["pt","es"]){c.copy[lang]=c.copy[lang]||{};for(const [key] of COPY_FIELDS)c.copy[lang][key]=$(`copy-${lang}-${key}`).value.trim()}c.copy.pt.vognText=vognTextPt.value.trim();c.copy.es.vognText=vognTextEs.value.trim();c.copy.pt.glitzyText=glitzyTextPt.value.trim();c.copy.es.glitzyText=glitzyTextEs.value.trim();c.sections={};document.querySelectorAll("[data-section-key]").forEach(x=>c.sections[x.dataset.sectionKey]=x.checked);return c}
async function save(){status("Salvando…");const r=await fetch("/api/admin/content",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(collect())});if(r.status===401)return showLogin("Sessão expirada");const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){status(d.error||"Erro ao salvar");alert(d.error||"Erro ao salvar");return}fill(d.config);status("Alterações publicadas",true)}
loginForm.addEventListener("submit",async e=>{e.preventDefault();loginError.textContent="";const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:password.value})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok){loginError.textContent=d.error||"Erro ao entrar";return}password.value="";await load()});
logoutBtn.addEventListener("click",async()=>{await fetch("/api/admin/logout",{method:"POST"});showLogin()});reloadBtn.onclick=load;saveTop.onclick=save;saveBottom.onclick=save;
mapEmbedUrl.addEventListener("input",()=>{mapPreview.src=mapEmbedUrl.value});vognPhoto.addEventListener("input",()=>setPreview(vognPreview,vognPhoto.value,"DJ VOGN"));glitzyPhoto.addEventListener("input",()=>setPreview(glitzyPreview,glitzyPhoto.value,"DJ GLITZY"));
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-lang]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll("[data-panel]").forEach(p=>p.classList.toggle("active",p.dataset.panel===b.dataset.lang))});
document.querySelectorAll("[data-upload]").forEach(btn=>btn.onclick=async()=>{const slot=btn.dataset.upload,file=$(slot+"File").files[0];if(!file)return alert("Selecione uma imagem");btn.disabled=true;btn.textContent="Enviando…";try{const fd=new FormData();fd.append("file",file);fd.append("slot",slot);const r=await fetch("/api/admin/upload",{method:"POST",body:fd});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Falha no upload");$(slot+"Photo").value=d.url;setPreview($(slot+"Preview"),d.url,slot);status("Imagem enviada. Salve as alterações.",true)}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent="Enviar foto"}});
buildCopyFields();buildSections();load();
